In [1]:
import scraper as s
import pandas as pd
import numpy as np
import datetime

In [2]:
m = s.stockMongo()
apple = m.get_options("AAPL")

In [3]:
apple.head()

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-06-09 04:56:55.325,0.00,0.00,AAPL210917C00110000,in-the-money,0.00%,197.67,2020-05-15,110.0,2021-09-17,Call,1.0
2020-06-09 04:56:55.325,147.45,138.05,AAPL210917C00120000,in-the-money,0.00%,122.30,2019-10-22,120.0,2021-09-17,Call,NaN
2020-06-09 04:56:55.325,209.50,204.50,AAPL210917C00125000,in-the-money,44.92%,179.31,2020-05-07,125.0,2021-09-17,Call,494.0
2020-06-09 04:56:55.325,0.00,0.00,AAPL210917C00130000,in-the-money,0.00%,201.75,2020-06-05,130.0,2021-09-17,Call,5.0
2020-06-09 04:56:55.325,178.60,175.30,AAPL210917C00135000,in-the-money,0.00%,136.69,2020-04-09,135.0,2021-09-17,Call,3.0

In [7]:
apple = apple.where(apple['last_trade']==apple.index.date).dropna()

In [8]:
apple = apple['2020-06-09'].where(apple['2020-06-09']['strike-date']=='2021-09-17').dropna()

In [9]:
apl = m.get_finnhub_prices('AAPL', datetime.datetime.fromisoformat('2020-06-09'), datetime.datetime.now())

In [10]:
apl['date'] = pd.to_datetime(apl.index, "%Y-%m-%d")

In [12]:
apl.reset_index()

            t       c       h       l       o         v       date
0  2020-06-09  343.99  345.61  332.01  332.14  36928100 2020-06-09
1  2020-06-10  352.84  354.77  346.09  347.90  41662900 2020-06-10
2  2020-06-11  335.90  351.06  335.48  349.31  50415600 2020-06-11
3  2020-06-12  338.80  347.80  334.22  344.72  50001500 2020-06-12
4  2020-06-15  342.99  345.68  332.58  333.25  34702200 2020-06-15
5  2020-06-16  352.08  353.20  344.72  351.46  41357200 2020-06-16
6  2020-06-17  351.59  355.40  351.09  355.15  28532000 2020-06-17
7  2020-06-18  351.73  353.45  349.22  351.41  24205100 2020-06-18
8  2020-06-19  349.72  356.56  345.15  354.64  66119000 2020-06-19
9  2020-06-22  358.87  359.46  351.15  351.34  33861300 2020-06-22
10 2020-06-23  366.53  372.38  362.27  364.00  53038900 2020-06-23
11 2020-06-24  360.06  368.79  358.52  365.00  48155800 2020-06-24
12 2020-06-25  364.84  365.00  357.57  360.70  34380600 2020-06-25
13 2020-06-26  353.63  365.32  353.02  364.41  51314200 2020-06-26
14 2020-06-29  361.78  362.17  351.28  353.25  32661500 2020-06-29
15 2020-06-30  364.80  365.98  360.00  360.08  35055800 2020-06-30
16 2020-07-01  364.11  367.36  363.91  365.12  27684300 2020-07-01
17 2020-07-02  364.11  370.47  363.64  367.85  28510400 2020-07-02
18 2020-07-06  373.85  375.78  369.87  370.00  29663900 2020-07-06
19 2020-07-07  372.69  378.62  372.23  375.41  28106100 2020-07-07
20 2020-07-08  381.37  381.50  376.36  376.72  29273000 2020-07-08
21 2020-07-09  383.01  385.27  378.69  385.05  31410700 2020-07-09
22 2020-07-10  383.68  383.92  378.82  381.34  22564300 2020-07-10
23 2020-07-13  381.91  399.82  381.03  389.06  47912300 2020-07-13
24 2020-07-14  388.23  389.02  375.51  379.36  42747300 2020-07-14
25 2020-07-15  390.90  396.99  385.96  395.96  38299500 2020-07-15
26 2020-07-16  386.09  389.62  383.62  386.25  27644400 2020-07-16
27 2020-07-17  385.31  388.59  383.36  387.95  23046700 2020-07-17
28 2020-07-20  393.43  394.00  384.25  385.67  22579500 2020-07-20
29 2020-07-21  388.00  397.00  386.97  396.69  25911500 2020-07-21
30 2020-07-22  389.09  391.90  386.41  386.77  22250400 2020-07-22
31 2020-07-23  371.38  388.31  368.04  387.99  49251100 2020-07-23
32 2020-07-24  370.46  371.88  356.58  363.95  46359700 2020-07-24
33 2020-07-27  379.24  379.62  373.92  374.84  59134131 2020-07-27
34 2020-07-28  373.01  378.20  372.99  377.47  25864000 2020-07-28
35 2020-07-29  380.16  380.92  374.85  375.00  21497602 2020-07-29

In [16]:
apl.where(apl['date']=='2020-06-09').dropna()

                 c       h       l       o           v       date
t
2020-06-09  343.99  345.61  332.01  332.14  36928100.0 2020-06-09

In [29]:
apple_calls = apple.where(apple['type']=="Call").dropna()
apple_puts = apple.where(apple['type']=="Put").dropna()

In [78]:
matrix = []
for i in range(len(apple_calls)-1):
    for j in range(len(apple_puts)-1):
        matrix.append([[apple_calls.iloc[i+1,2], apple_calls.iloc[i,2], apple_puts.iloc[j+1,2], apple_puts.iloc[j,2]],
                       apple_calls.iloc[i+1,7]-apple_calls.iloc[i,7]+apple_puts.iloc[j+1,7]-apple_puts.iloc[j,7],
                        apple_calls.iloc[i+1,5]-apple_calls.iloc[i,5]+apple_puts.iloc[j+1,5]-apple_puts.iloc[j,5],
                       [apple_calls.iloc[i+1,7],apple_calls.iloc[i,7],apple_puts.iloc[j+1,7],apple_puts.iloc[j,7]],
                      ])
matrix[0]

[['AAPL210917C00200000',
  'AAPL210917C00190000',
  'AAPL210917P00180000',
  'AAPL210917P00110000'],
 80.0,
 -4.4199999999999875,
 [200.0, 190.0, 180.0, 110.0]]

In [74]:
apple_calls.where(apple_calls['strike']>343.99).dropna()

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-06-09 21:09:17.973,42.75,40.90,AAPL210917C00350000,in-the-money,29.33%,41.62,2020-06-09,350.0,2021-09-17,Call,282.0
2020-06-09 21:09:17.973,38.20,36.60,AAPL210917C00360000,in-the-money,28.96%,38.50,2020-06-09,360.0,2021-09-17,Call,204.0
2020-06-09 21:09:17.973,33.95,32.15,AAPL210917C00370000,in-the-money,28.58%,33.50,2020-06-09,370.0,2021-09-17,Call,14.0
2020-06-09 21:09:17.973,29.95,28.50,AAPL210917C00380000,in-the-money,28.15%,29.35,2020-06-09,380.0,2021-09-17,Call,27.0
2020-06-09 21:09:17.973,26.50,25.25,AAPL210917C00390000,in-the-money,27.88%,25.85,2020-06-09,390.0,2021-09-17,Call,25.0
2020-06-09 21:09:17.973,23.10,21.70,AAPL210917C00400000,in-the-money,27.44%,22.40,2020-06-09,400.0,2021-09-17,Call,31.0
2020-06-09 21:09:17.973,17.95,16.80,AAPL210917C00420000,in-the-money,27.12%,17.50,2020-06-09,420.0,2021-09-17,Call,24.0
2020-06-09 21:09:17.973,15.70,14.20,AAPL210917C00430000,in-the-money,26.93%,15.60,2020-06-09,430.0,2021-09-17,Call,1.0
2020-06-09 21:09:17.973,13.70,12.70,AAPL210917C00440000,in-the-money,26.75%,13.60,2020-06-09,440.0,2021-09-17,Call,2.0
2020-06-09 21:09:17.973,11.85,11.00,AAPL210917C00450000,in-the-money,26.53%,11.67,2020-06-09,450.0,2021-09-17,Call,8.0
2020-06-09 21:09:17.973,10.20,9.20,AAPL210917C00460000,in-the-money,26.29%,9.25,2020-06-09,460.0,2021-09-17,Call,1.0
2020-06-09 21:09:17.973,8.00,6.90,AAPL210917C00480000,in-the-money,26.41%,7.85,2020-06-09,480.0,2021-09-17,Call,2.0
2020-06-09 21:09:17.973,6.70,5.60,AAPL210917C00500000,in-the-money,27.02%,6.15,2020-06-09,500.0,2021-09-17,Call,5.0

In [76]:
apple_puts.where(apple_puts['strike']<343.99).dropna()

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-06-09 21:09:17.973,1.83,1.21,AAPL210917P00110000,in-the-money,54.98%,1.50,2020-06-09,110.0,2021-09-17,Put,10.0
2020-06-09 21:09:17.973,5.25,4.50,AAPL210917P00180000,in-the-money,43.51%,5.00,2020-06-09,180.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,5.55,4.50,AAPL210917P00185000,in-the-money,42.60%,5.20,2020-06-09,185.0,2021-09-17,Put,5.0
2020-06-09 21:09:17.973,7.05,6.20,AAPL210917P00200000,in-the-money,40.90%,6.05,2020-06-09,200.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,11.05,10.00,AAPL210917P00230000,in-the-money,37.87%,10.15,2020-06-09,230.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,12.65,11.60,AAPL210917P00240000,in-the-money,36.86%,12.75,2020-06-09,240.0,2021-09-17,Put,6.0
2020-06-09 21:09:17.973,14.55,13.55,AAPL210917P00250000,in-the-money,36.00%,15.00,2020-06-09,250.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,16.75,15.70,AAPL210917P00260000,in-the-money,35.26%,16.00,2020-06-09,260.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,21.95,20.80,AAPL210917P00280000,in-the-money,33.90%,21.00,2020-06-09,280.0,2021-09-17,Put,57.0
2020-06-09 21:09:17.973,28.45,27.05,AAPL210917P00300000,in-the-money,32.78%,27.67,2020-06-09,300.0,2021-09-17,Put,4.0
2020-06-09 21:09:17.973,32.15,30.20,AAPL210917P00310000,in-the-money,32.25%,31.43,2020-06-09,310.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,36.15,34.20,AAPL210917P00320000,in-the-money,31.72%,35.42,2020-06-09,320.0,2021-09-17,Put,2.0
2020-06-09 21:09:17.973,40.60,39.00,AAPL210917P00330000,in-the-money,31.30%,39.40,2020-06-09,330.0,2021-09-17,Put,7.0
2020-06-09 21:09:17.973,45.25,43.55,AAPL210917P00340000,in-the-money,30.80%,43.44,2020-06-09,340.0,2021-09-17,Put,33.0